#!/bin/bash
# Resets de report if already exists (or rewrite on it). Shows hostname, current user and the current date.
echo "System Report for $(hostname) generated by $(whoami), on $(date '+%Y-%m-%d')" > generatedReport.txt
echo "" >> generatedReport.txt

#Start first part of system information.
echo "System Information" >> generatedReport.txt
echo "------------------" >> generatedReport.txt
#Get the distro and version.
source /etc/os-release && nameAndVersion="$NAME $VERSION"
echo "OS: $nameAndVersion" >> generatedReport.txt
#Get the uptime.
uptimeVariable=$(uptime -p)
echo "Uptime: $uptimeVariable" >> generatedReport.txt
#Get the CPU, processor make and model.
processorModel=$(grep "model name" /proc/cpuinfo | head -1 | cut -c 14-)
echo "CPU: $processorModel" >> generatedReport.txt
#Get the RAM.
RAM=$(free -m | grep Mem | awk '{print $2}')
echo "RAM: $RAM MB" >> generatedReport.txt
#Get disks.
echo "Disk(s): " >> generatedReport.txt
echo $(sudo lshw -class disk | grep -E "product|vendor|size") >> generatedReport.txt
#Get video.
echo "Video: $(sudo lspci | grep -i vga)" >> generatedReport.txt

#Get the host address interface and default gateway address.
defaultInterface=$(ip -4 addr show $(ip -4 route show default | awk '{print $5}') | grep -oP 'inet \K[\d.]+')
echo "Host Address: $defaultInterface" >> generatedReport.txt
#Get the default gateway.
defaultGateway=$(ip -4 route show default | awk '{print $3}')
echo "Gateway IP: $defaultGateway" >> generatedReport.txt
#Get the DNS server.
dns_server=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')
echo "DNS Server: $dns_server" >> generatedReport.txt

#Line space.
echo "" >> generatedReport.txt

#Start of the report of the system status.
echo "System status" >> generatedReport.txt
echo "-------------" >> generatedReport.txt
#Detect users.
activeUsers=$(who | awk '{print $1}' | uniq)
echo "Users logged in: $activeUsers" >> generatedReport.txt
#Disk space.
diskSpace=$(df -h --local | awk '{print $6, $4}')
echo "Disk Space: $diskSpace" >> generatedReport.txt
#Process count.
processCount=$(ps -e | wc -l)
echo "Process count: $processCount" >> generatedReport.txt
#Load averages.
loadAverages=$(uptime | awk -F'load average' '{print $2}')
echo "Load Averages: $loadAverages" >> generatedReport.txt
#Listen ports.
ports=$(ss -tuln | awk '{print $5'} | awk -F: '{print $NF}' | uniq | paste -sd,)
echo "Listening Network Ports: $ports" >> generatedReport.txt
#UFW Status.
UFW_status=$(sudo ufw status | awk '/Status/ {print $2}')
echo "UFW Status: $UFW_status" >> generatedReport.txt

#Document generated location.
echo ""
echo "The report was created in the directory: $(pwd)" >> generatedReport.txt

cat generatedReport.txt
